#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftwheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightwheel,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     shoulder,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     elbow,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,      ,             tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    claw,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

/* void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}
*/

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  //initializeRobot();

  //waitForStart();   // wait for start of tele-op phase

  while (true)
  {

getJoystickSettings(joystick);
 if(joystick.joy1_y1 < 5 && joystick.joy1_y1 > -5)//deadzone leftwheel
	{
		motor(leftwheel) = 0;
	}
	if(joystick.joy1_y1 >= 5) //if joy value is positive move leftwheel forward
	{
		motor(leftwheel) = (joystick.joy1_y1* joystick.joy1_y1) / 100;
	}
	if(joystick.joy1_y1 <= -5)//if joy value is negative move wheel backwards
	{
		motor(leftwheel) = (joystick.joy1_y1 * joystick.joy1_y1) / -100;
	}


	if(joystick.joy1_y2 < 5 && joystick.joy1_y2 > -5)
	{
		motor(rightwheel) = 0;
	}
	if (joystick.joy1_y2 >= 5 )
	{
		motor(rightwheel) = (joystick.joy1_y2 * joystick.joy1_y2) / 100;
	}
	if (joystick.joy1_y2 <= -5)
	{
		motor(rightwheel) = (joystick.joy1_y2 * joystick.joy1_y2) / -100;
	}

	// Scooch forwards
		if(joy1Btn(4)==1)
		{
			motor[rightwheel]=20;
			motor[leftwheel]=20;
			wait1Msec(40);
		}
				// Scooch right
		if(joy1Btn(3)==1)
		{
			motor[rightwheel]=20;
			motor[leftwheel]=0;
			wait10Msec(4);
		}
  // Scooch backwards
		if(joy1Btn(2)==1)
		{
			motor[rightwheel]=-20;
			motor[leftwheel]=-20;
			wait1Msec(40);
		}
		// Scooch left
		if(joy1Btn(1)==1)
		{
			motor[leftwheel]=20;
			motor[rightwheel]=0;
			wait1Msec(40);
		}

	if(joystick.joy2_y1 < 5 && joystick.joy2_y1 > -5)
	{
		motor(elbow) = 0;
	}
	else
	{
		motor(elbow) = joystick.joy2_y1;
	}
	if(joystick.joy2_y2 < 5 && joystick.joy2_y2 > -5)
	{
		motor(shoulder) = 0;
	}
	else
	{
		motor(shoulder) = joystick.joy2_y2;
	}
	if(joy2Btn(3) == 1)
	{
		 servo[dump] = 16;
		 wait1Msec(100);
	}
	if(joy2Btn(1) == 1)
	{
	  servo[dump] = 149;
	  // dump out
	  wait1Msec(100);
	}
		if(joy2Btn(7) == 1)
	{
		 servo[claw] =  0;
		 //claw closed
		 wait1Msec(100);
	}

		if(joy2Btn(8) == 1)
	{
		 servo[claw] = 64;
		 wait1Msec(100);
	}
		if(joy2Btn(6) == 1)
	{
		servo[wrist] = ServoValue[wrist] - 1;
	}
	if(joy2Btn(5) == 1)
	{
		servo[wrist] = ServoValue[wrist] + 1;
	}
	if(joy1Btn(5) == 1)
	{
		motor(spinner)=100;
		wait1Msec(5);
	}
	else
	{
		motor(spinner)=0;
	}

	if(joy1Btn(6) == 1)
	{
		motor(spinner) = 20;
	}
	else
	{
		motor(spinner)=0;
	}

		// Insert code to have servos and motors respond to joystick and button values.

    // Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
    // You may be able to find "snippets" of code that are similar to the functions that you want to
    // perform.
  }
}
