#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     SMUX,           sensorI2CCustom)
#pragma config(Sensor, S3,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     ,               sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     leftwheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightwheel,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
#include "hitechnic-sensormux.h"
#include "lego-light.h"
#include "lego-touch.h"
#include "hitechnic-gyro.h"


//const tMUXSensor touch = msensor_S2_1;
//const tMUXSensor touch2 = msensor_S2_2;
const tMUXSensor LEGOLS = msensor_S2_3;

task main()
{
  initializeRobot();

 LSsetActive(LEGOLS);//set the Light sensor

 float rotSpeed = 0; //calibrate gyro
  float heading = 0;
	float offset = 590;
  // Calibrate the gyro, make sure you hold the sensor still
  HTGYROstartCal(HTGYRO);

  /* Add IR program
	*/

while(LSvalNorm(LEGOLS) < 26)
{
	motor(leftwheel) = -25; // Go foreward
	motor(rightwheel)= -25;
}
motor(leftwheel) = 0;
motor(rightwheel) = 0;
wait1Msec(1000);//change wait time for compitition

 while (heading < 90)
  {
   motor(leftwheel) = 0;
   motor(rightwheel) = -20;
   wait1Msec(10);

    // Read the current rotation speed
    rotSpeed = SensorValue(HTGYRO)- offset;

    // Calculate the new heading by adding the amount of degrees
    // we've turned in the last 20ms
    // If our current rate of rotation is 100 degrees/second,
    // then we will have turned 100 * (20/1000) = 2 degrees since
    // the last time we measured.
    heading = heading + rotSpeed * 0.01;
  }

 motor(leftwheel) = 0;
 motor(rightwheel) = 0;
 wait1Msec(1000); //change value

 motor(leftwheel) = -30;
 motor(rightwheel) = -30;
 wait1Msec(1500); //change to how long it takes to climb ramp

 motor(leftwheel) = 0;
 motor(rightwheel) = 0;
 wait1Msec(2000);



}
