#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     leftwheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightwheel,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int count;
task main()
{
while(SensorValue(IR) != 5)

	{
		motor(leftwheel)=25; // Go foreward
		motor(rightwheel)=25;

	}


{
	motor(leftwheel) = 0; // Tank Turn
	motor(rightwheel) = 25;
	wait1Msec(1100);
}


	motor(leftwheel) = 0; // Stop
	motor(rightwheel) = 0;

	wait1Msec(1000);

	while(SensorValue(touch) != 1)
	{
		motor(leftwheel) = 25; // Go foreward
		motor(rightwheel)=25;
	}
}
