#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftwheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightwheel,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int count;
#include "hitechnic-sensormux.h"
#include "hitechnic-gyro.h"
#include "hitechnic-irseeker-v2.h"
#include "lego-light.h"
#include "lego-touch.h"

const tMUXSensor touch = msensor_S2_1;
const tMUXSensor light = msensor_S2_2;
const tMUXSensor IRRight = msensor_S2_3;
const tMUXSensor IRLeft = msensor_S2_4;


task main()
{
	/*while(SensorValue(msensor_S2_3) != 5)

	{
		motor(leftwheel)=25; // Go foreward
		motor(rightwheel)=25;
		count = count + 1;
	}

	motor(leftwheel) = -25; // Tank Turn
	motor(rightwheel) = 25;

	wait1Msec(710);

	motor(leftwheel) = 0; // Stop
	motor(rightwheel) = 0;

	wait1Msec(1000);*/

	while( != 1)
	{
		motor(leftwheel) = 25; // Go foreward
		motor(rightwheel)=25;
	}
}
