#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     leftwheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightwheel,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue(light) < 25)
	{
		motor(leftwheel) = -25;
		motor(rightwheel) = -25;
	}
	motor(leftwheel) = 0;
	motor(rightwheel) = -25;

	wait1Msec(1000);

	motor(leftwheel) = 0;
	motor(rightwheel) = 0;

	wait1Msec(1000);

	motor(leftwheel)=-50;
	motor(rightwheel)=-50;

	wait1Msec(1000);
}
