#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     HTSMUX,               sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftwheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightwheel,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "hitechnic-sensormux.h"
#include "lego-touch.h"


const tMUXSensor LEGOTOUCH = msensor_S2_1;
task main()
{



  while (true)
  	{
    // Check if the sensor is pressed or not.
    if (TSreadState(LEGOTOUCH))
    {
    	motor(rightwheel) = 20;
      motor(leftwheel) = 20;
  }
  }

}
